### ISSUE TITLE
Blik 0 payment type (in-store) throws SERVICE_NOT_FOUND error

### ISSUE THREAD

**Issue by pshemek** [bluepayment-plugin/bluemedia-payment-gateway-for-woocommerce#3]
`11-11-2011 @ 11:11:11 - qwertyqwertyqwertyqwerty [BM Bluepayment] Error when calling init transaction in BlueMedia gateway
11-11-2011 @ 11:11:11 - qwertyqwertyqwertyqwerty [BM Bluepayment] Transaction data:{"ServiceID":99999,"OrderID":"100","Amount":"52.00","Description":"100","GatewayID":"509","Currency":"PLN","CustomerEmail":"client@example.com","CustomerIP":"11.222.333.44","Title":"P\u0142atno\u015b\u0107 BLIK","AuthorizationCode":"1234567","ScreenType":"FULL","Hash":"111111111111111111111111"}
11-11-2011 @ 11:11:11 - qwertyqwertyqwertyqwerty RuntimeException: SERVICE_NOT_FOUND in /home/clients/www/123456789/wp-content/plugins/bluemedia-payment-gateway-for-woocommerce-master/bluemedia-sdk-php/src/Gateway.php:131
Stack trace:
#0 /home/clients/www/123456789/wp-content/plugins/bluemedia-payment-gateway-for-woocommerce-master/bluemedia-sdk-php/src/Gateway.php(487): BlueMedia\OnlinePayments\Gateway->parseInitTransferResponse()
#1 /home/clients/www/123456789/wp-content/plugins/bluemedia-payment-gateway-for-woocommerce-master/handler/InitTransactionHandler.php(8): BlueMedia\OnlinePayments\Gateway->doInitTransaction()
#2 /home/clients/www/123456789/wp-content/plugins/bluemedia-payment-gateway-for-woocommerce-master/handler/BlueMediaSdkHandler.php(31): InitTransactionHandler->handle()
#3 /home/clients/www/123456789/wp-content/plugins/bluemedia-payment-gateway-for-woocommerce-master/classes/wc-payment-gateway-bluemedia-blik-zero.php(101): BlueMediaSdkHandler->call()
#4 /home/clients/www/123456789/wp-content/plugins/bluemedia-payment-gateway-for-woocommerce-master/validator/BlikTransactionValidator.php(25): WC_Payment_Gateway_BlueMedia_Blik_Zero->validate_blik_transaction()
#5 /home/clients/www/123456789/wp-includes/class-wp-hook.php(303): BlikTransactionValidator::validate()
#6 /home/clients/www/123456789/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /home/clients/www/123456789/wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /home/clients/www/123456789/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action()
#9 /home/clients/www/123456789/wp-includes/class-wp-hook.php(303): WC_AJAX::do_wc_ajax()
#10 /home/clients/www/123456789/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#11 /home/clients/www/123456789/wp-includes/plugin.php(470): WP_Hook->do_action()
#12 /home/clients/www/123456789/wp-includes/template-loader.php(13): do_action()
#13 /home/clients/www/123456789/wp-blog-header.php(19): require_once('/home/clients/w...')
#14 /home/clients/www/123456789/index.php(17): require('/home/clients/w...')
#15 {main}`

**Comment by BlueMediaDev** [comment]
Dzień dobry

zachęcamy do pobrania aktualnych wersji modułu, w których wprowadziliśmy sporo zmian i ulepszeń.

pozdrawiamy
zespół Blue Media
